### ISSUE TITLE
1.18.2 support

### ISSUE THREAD

**Issue by Drc-DEV** [InventivetalentDev/GlowAPI#114]
GlowAPI spams errors on 1.18.2
`
[16:16:52 WARN]: [GlowAPI] Task #5025 for GlowAPI v1.5.2-SNAPSHOT generated an exception java.lang.NoClassDefFoundError: Could not initialize class org.inventivetalent.glow.reflection.minecraft.Minecraft at org.inventivetalent.glow.reflection.resolver.minecraft.OBCClassResolver.resolve(OBCClassResolver.java:15) ~[GlowAPI-1.5.2.jar:?] at org.inventivetalent.glow.GlowAPI.getEntityById(GlowAPI.java:654) ~[GlowAPI-1.5.2.jar:?] at org.inventivetalent.glow.GlowAPI$1.lambda$onSend$0(GlowAPI.java:587) ~[GlowAPI-1.5.2.jar:?] at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-242] at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-242] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.18.2.jar:git-Paper-242] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-242] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[paper-1.18.2.jar:git-Paper-242] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[paper-1.18.2.jar:git-Paper-242] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-242] at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by kiloRs** [comment]
Can we get an update on this?
