### ISSUE TITLE
1.19 Issues

### ISSUE THREAD

**Issue by Simmo06** [InventivetalentDev/GlowAPI#141]
Server Ver Paper 1.19.4
Using Latest GLOWAPI distro.

``` java
GlowAPI]: [STDOUT] [ReflectionHelper/MinecraftVersion] Injected dynamic version v1_19_R3 (#11903).
**[GlowAPI]: [STDOUT] [ReflectionHelper/MinecraftVersion] Please inform inventivetalent about the outdated version, as this is not guaranteed to work.**
ERROR10:24:30
[GlowAPI]: [STDERR] [ReflectionHelper] Failed to find version enum for 'org.bukkit.craftbukkit.v1_19_R3'/'v1_19_R3'
INFO10:24:30
[GlowAPI]: [STDOUT] [ReflectionHelper] Generating dynamic constant...
[GlowAPI]: [STDOUT] [ReflectionHelper] Failed to create deprecated dynamic version
[GlowAPI]: [STDOUT] [ReflectionHelper] If the above (ReflectionHelper/MinecraftVersion) succeeded, you can ignore this.
WARN10:24:30
java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='constructorAccessor', types=[]}]: in class class java.lang.reflect.Constructor
at GlowAPI_v1.5.6-SNAPSHOT.jar//org.inventivetalent.glow.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:252)
at GlowAPI_v1.5.6-SNAPSHOT.jar//org.inventivetalent.glow.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:12)
at GlowAPI_v1.5.6-SNAPSHOT.jar//org.inventivetalent.glow.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:63)
at GlowAPI_v1.5.6-SNAPSHOT.jar//org.inventivetalent.glow.reflection.resolver.FieldResolver.resolve(FieldResolver.java:69)
at GlowAPI_v1.5.6-SNAPSHOT.jar//org.inventivetalent.glow.reflection.minecraft.Minecraft.newEnumInstance(Minecraft.java:301)
at GlowAPI_v1.5.6-SNAPSHOT.jar//org.inventivetalent.glow.reflection.minecraft.Minecraft$Version.getVersion(Minecraft.java:267)
at GlowAPI_v1.5.6-SNAPSHOT.jar//org.inventivetalent.glow.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:45)
at GlowAPI_v1.5.6-SNAPSHOT.jar//org.inventivetalent.glow.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:26)
at GlowAPI_v1.5.6-SNAPSHOT.jar//org.inventivetalent.glow.GlowAPI$Color.<init>(GlowAPI.java:583)
at GlowAPI_v1.5.6-SNAPSHOT.jar//org.inventivetalent.glow.GlowAPI$Color.<clinit>(GlowAPI.java:559)
at GlowAPI_v1.5.6-SNAPSHOT.jar//org.inventivetalent.glow.GlowAPI.initTeam(GlowAPI.java:380)
at GlowAPI_v1.5.6-SNAPSHOT.jar//org.inventivetalent.glow.GlowAPI.initTeam(GlowAPI.java:391)
at GlowAPI_v1.5.6-SNAPSHOT.jar//org.inventivetalent.glow.GlowAPI.onJoin(GlowAPI.java:607)
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor851.execute(Unknown Source)
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
at net.minecraft.server.players.PlayerList.a(PlayerList.java:330)
at net.minecraft.server.network.LoginListener.a(LoginListener.java:202)
at net.minecraft.server.network.LoginListener.d(LoginListener.java:183)
at net.minecraft.server.network.LoginListener.c(LoginListener.java:85)
at net.minecraft.network.NetworkManager.a(NetworkManager.java:595)
at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:234)
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1576)
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by srnyx** [comment]
https://github.com/WarpedRealm/WarpedGlowAPI
https://media.srnyx.com/r/GlowAPI_v1.5.7-SNAPSHOT.jar

**Comment by joeyblog** [comment]
@srnyx
Your code has a bug.

https://github.com/WarpedRealm/WarpedGlowAPI/blob/3c7305f19e03484fc9926639c644107193934741/src/org/inventivetalent/glow/GlowAPI.java#L92

`entity.setGlowing(true);`

This always enbales the glow regardless of glowing boolean.
Also, white glow is visible to other players, probably because you are not using
`sendGlowPacket(Entity entity, boolean wasGlowing, boolean glowing, Player receiver)`

**Comment by srnyx** [comment]
> @srnyx Your code has a bug.

It's not my code, I've also noticed some bugs with it and just ended up not using it and sticking to GlowAPI 1.19.2.
WarpedGlowAPI's developer is also not responding (tried friending them on Discord). I've requested another developer to make a new fork of GlowAPI that would be similar to WarpedGlowAPI except be maintained and actually work...

**Comment by joeyblog** [comment]
oops, sorry!
I see. I was trying to use it in 1.19.4 ver but I might wanna lower it to 1.19.2 then.
Also with the crouch bug, its a tough situation here :/

**Comment by srnyx** [comment]
Found a new one that seems to work good: https://github.com/SkytAsul/GlowingEntities

**Comment by joeyblog** [comment]
Oh thanks for sharing! I will give it a try.

**Comment by iHDeveloper** [comment]
Hello there! I will try to look into this issue and solve it during those two days.

I apologize for not noticing it earlier 😅

**Comment by joeyblog** [comment]
Thank you! 
I look forward to the update :)

**Comment by iHDeveloper** [comment]
Sorry for the delay, The changes in 1.19 and 1.20 seems a little complicated due to Mojang changing the format of some packets. But, I will be able to work it them around shortly inshallah.
