### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by bladeRR** [InventivetalentDev/GlowAPI#142]
```
[18:19:53 ERROR]: Could not pass event PlayerJoinEvent to GlowAPI v1.5.7-SNAPSHOT
java.lang.IllegalArgumentException: object is not an instance of declaring class
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.inventivetalent.glow.GlowAPI.sendPacket(GlowAPI.java:576) ~[GlowAPI_v1.5.7-SNAPSHOT.jar:?]
        at org.inventivetalent.glow.GlowAPI.sendTeamPacket(GlowAPI.java:549) ~[GlowAPI_v1.5.7-SNAPSHOT.jar:?]
        at org.inventivetalent.glow.GlowAPI.initTeam(GlowAPI.java:384) ~[GlowAPI_v1.5.7-SNAPSHOT.jar:?]
        at org.inventivetalent.glow.GlowAPI.initTeam(GlowAPI.java:394) ~[GlowAPI_v1.5.7-SNAPSHOT.jar:?]
        at org.inventivetalent.glow.GlowAPI.onJoin(GlowAPI.java:635) ~[GlowAPI_v1.5.7-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1297.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-43]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-43]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:339) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:599) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1585) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-43]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Faobi69** [comment]
yes i have the same problem

**Comment by srnyx** [comment]
The issue occurs on 1.19.4+ (I assume 1.19.3 too) because the plugin doesn't support those versions yet
I tried to add support myself but I honestly can barely understand the code and some of the reflected classes aren't even matching up with what I'm finding on https://mappings.cephx.dev

**Comment by srnyx** [comment]
@InventivetalentDev Please come back to this API, it's the only good glow API, I've tried so many... 😭
