### ISSUE TITLE
1.4.4 PlayerJoinEvent NPE

### ISSUE THREAD

**Issue by CyberSecGuy** [InventivetalentDev/GlowAPI#2]
GlowAPI v1.4.4 - PlayerJoinEvent NPE.

```
[22:00:17] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to GlowAPI v1.4.4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-90f61bc-83a9dbd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-90f61bc-83a9dbd]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-90f61bc-83a9dbd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.PlayerList.disconnect(PlayerList.java:385) [server.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1061) [server.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.NetworkManager.handleDisconnection(NetworkManager.java:318) [server.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:174) [server.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:827) [server.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [server.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [server.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [server.jar:git-Spigot-90f61bc-83a9dbd]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at org.inventivetalent.packetlistener.ChannelInjector.removeChannel(ChannelInjector.java:79) ~[?:?]
        at org.inventivetalent.packetlistener.PacketListenerAPI.onQuit(PacketListenerAPI.java:122) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor636.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-90f61bc-83a9dbd]
        ... 12 more
```

**Comment by InventivetalentDev** [comment]
Please provide more details than that. It gives you a template for a reason.

**Comment by bluefutureMC** [comment]
For Me It Gives The Effect But Not The Color Of It.

**Comment by InventivetalentDev** [comment]
@bluefutureMC Assuming you are _blue_future_ on the forums, please open a separate issue and include your code and provide more details.
