### ISSUE TITLE
1.16.4 support

### ISSUE THREAD

**Issue by Patbox** [InventivetalentDev/GlowAPI#78]
## What steps will reproduce the problem?  
1. Update server to 1.16.4
2. Join it.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
[18:06:15 INFO]: GlowAPI version 1.4.13-SNAPSHOT

## What Spigot version are you using? *Type /version*  
[18:05:49 INFO]: This server is running Tuinity version git-Tuinity-"0850468" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
```
[18:01:18] [Netty Server IO #3/WARN]: [PacketListenerAPI] An exception occured while trying to execute 'onSend' in plugin GlowAPI: java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='net.minecraft.server.v1_16_R3.IntHashMap', types=[]}]
[18:01:18] [Netty Server IO #3/WARN]: java.lang.RuntimeException: java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='net.minecraft.server.v1_16_R3.IntHashMap', types=[]}]
[18:01:18] [Netty Server IO #3/WARN]: 	at org.inventivetalent.glow.GlowAPI.getEntityById(GlowAPI.java:594)
[18:01:18] [Netty Server IO #3/WARN]: 	at org.inventivetalent.glow.GlowAPI$1.onSend(GlowAPI.java:493)
[18:01:18] [Netty Server IO #3/WARN]: 	at org.inventivetalent.packetlistener.handler.PacketHandler.notifyHandlers(PacketHandler.java:81)
[18:01:18] [Netty Server IO #3/WARN]: 	at org.inventivetalent.packetlistener.PacketListenerAPI.onPacketSend(PacketListenerAPI.java:118)
[18:01:18] [Netty Server IO #3/WARN]: 	at org.inventivetalent.packetlistener.channel.ChannelAbstract.onPacketSend(ChannelAbstract.java:85)
[18:01:18] [Netty Server IO #3/WARN]: 	at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:140)
[18:01:18] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[18:01:18] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[18:01:18] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[18:01:18] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[18:01:18] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:697)
[18:01:18] [Netty Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
[18:01:18] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:284)
[18:01:18] [Netty Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.write(ChannelProxy.java:312)
[18:01:18] [Netty Server IO #3/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.lambda$writePacket$11(NetworkManager.java:439)
[18:01:18] [Netty Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:325)
[18:01:18] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[18:01:18] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[18:01:18] [Netty Server IO #3/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[18:01:18] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[18:01:18] [Netty Server IO #3/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:01:18] [Netty Server IO #3/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[18:01:18] [Netty Server IO #3/WARN]: Caused by: java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='net.minecraft.server.v1_16_R3.IntHashMap', types=[]}]
[18:01:18] [Netty Server IO #3/WARN]: 	at org.inventivetalent.glow.reflection.resolver.ClassResolver.notFoundException(ClassResolver.java:40)
[18:01:18] [Netty Server IO #3/WARN]: 	at org.inventivetalent.glow.reflection.resolver.ClassResolver.notFoundException(ClassResolver.java:8)
[18:01:18] [Netty Server IO #3/WARN]: 	at org.inventivetalent.glow.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:60)
[18:01:18] [Netty Server IO #3/WARN]: 	at org.inventivetalent.glow.reflection.resolver.ClassResolver.resolve(ClassResolver.java:27)
[18:01:18] [Netty Server IO #3/WARN]: 	at org.inventivetalent.glow.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:18)
[18:01:18] [Netty Server IO #3/WARN]: 	at org.inventivetalent.glow.GlowAPI.getEntityById(GlowAPI.java:584)
[18:01:18] [Netty Server IO #3/WARN]: 	... 21 more```

**Comment by sgdc3** [comment]
bump @InventivetalentDev

**Comment by Lorenzostuy** [comment]
add support for 1.16.3 / 1.16.4 whatever  @InventivetalentDev

**Comment by InventivetalentDev** [comment]
Did you try https://github.com/InventivetalentDev/GlowAPI/releases/tag/1.4.14-SNAPSHOT ?

**Comment by sgdc3** [comment]
Yep, it's working

**Comment by Rick-Sanchez-C** [comment]
hat steps will reproduce the problem?
Update server to 1.19.3
Active glow in any entitie
What version of the plugin are you using? Type /version <Plugin Name>
[18:06:15 INFO]: GlowAPI version 1.5.7-SNAPSHOT

What Spigot version are you using? Type /version
 This server is running Paper version git-Paper-371 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 035f9d7)

Do you have an error log? Use [pastebin.com](http://pastebin.com/). If you're not sure, upload your whole server log
The same error but for 1.19.3
