### ISSUE TITLE
Glow not work.

### ISSUE THREAD

**Issue by LowderPlay** [InventivetalentDev/GlowAPI#8]
Hello! Here is error in my server log:
`Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.inventivetalent.glow.reflection.minecraft.DataWatcher$V1_9$ValueType
	at org.inventivetalent.glow.GlowAPI.sendGlowPacket(GlowAPI.java:290) ~[?:?]
	at org.inventivetalent.glow.GlowAPI.setGlowing(GlowAPI.java:113) ~[?:?]
	at org.inventivetalent.glow.GlowAPI.setGlowing(GlowAPI.java:130) ~[?:?]
	at future.blue.fun.commands.SetGlow.onCommand(SetGlow.java:36) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-7fc5cd8]
	... 15 more`
What i will do?

**Comment by x9nico** [comment]
Hi @LowderPlay can you show me your code and your Main class ?

**Comment by x9nico** [comment]
and your plugin.yml
