### ISSUE TITLE
Glow API Error (API CLASS IS NOT INITIALIZED)

### ISSUE THREAD

**Issue by kiloRs** [InventivetalentDev/GlowAPI#84]
Error

`[03:26:12] [Server thread/INFO]: [GlowAPI] Enabling GlowAPI v1.4.15-SNAPSHOT*
[03:26:12] [Server thread/INFO]: [APIManager] API class 'org.inventivetalent.packetlistener.PacketListenerAPI' is not yet initialized. Creating new instance.
[03:26:12] [Server thread/ERROR]: Error occurred while enabling GlowAPI v1.4.15-SNAPSHOT (Is it up to date?)
java.lang.ClassCastException: class org.inventivetalent.packetlistener.PacketListenerAPI cannot be cast to class org.inventivetalent.apihelper.API (org.inventivetalent.packetlistener.PacketListenerAPI is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @1c21e7e0; org.inventivetalent.apihelper.API is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @5d2e05df)
	at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:116) ~[?:?]
	at org.inventivetalent.glow.GlowAPI.init(GlowAPI.java:472) ~[?:?]
	at org.inventivetalent.apihelper.RegisteredAPI.init(RegisteredAPI.java:55) ~[?:?]
	at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:96) ~[?:?]
	at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:127) ~[?:?]
	at org.inventivetalent.glow.GlowPlugin.onEnable(GlowPlugin.java:22) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1157]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Purpur-1157]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Purpur-1157]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Purpur-1157]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1157]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[patched_1.16.5.jar:git-Purpur-1157]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309) ~[patched_1.16.5.jar:git-Purpur-1157]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1157]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1157]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[03:26:12] [Server thread/INFO]: [GlowAPI] Disabling GlowAPI v1.4.15-SNAPSHOT
[03:26:12] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.24
[03:26:12] [Server thread/INFO]: [LibsDisguises] File Name: LibsDisguises-10.0.22-Premium.jar`

**Comment by cloakfox** [comment]
Getting same issue.

Running Airplane version git-Airplane-"a13c511" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Java 16

**Comment by lexikiq** [comment]
Duplicate of #83

**Comment by ItachidesSAMA** [comment]
Same error

**Comment by qixils** [comment]
This issue has been fixed for ages. Update your copy of GlowAPI.
